### ISSUE TITLE
ワードアート的なタイトル

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/bad-opendata-temple#11]
サイトトップのh1タイトルは、なんかすごい３Dっぽいワードアート的なやつにしたいです。

**Comment by kaizumaki** [comment]
@kyokoo-tagaki さんが作ってくれました！合掌 🙏 

![ti_bad-opendata-temple](https://user-images.githubusercontent.com/14883063/99143659-9ddd1000-26a2-11eb-97a7-53a78dfea991.png)

**Comment by kyokoo-tagaki** [comment]
こうしてみると普通ぽいなぁ。虹色にしたかったけど寺じゃないよねw
