### ISSUE TITLE
faviconを設定する

### ISSUE THREAD

**Issue by ocean3fish** [codeforjapan/bad-opendata-temple#111]
これとか？→ 🙏

**Comment by ocean3fish** [comment]
https://www.joypixels.com/emoji
Folded Hands

**Comment by halsk** [comment]
master に deploy したところ、[Build error](https://github.com/codeforjapan/bad-opendata-temple/runs/1467011818?check_suite_focus=true#step:9:31)になってしまったので、元に戻しました。

やったこと

1. `gatsby-plugin-manifest` を追加
2. `favicon.png` を追加
3. `gatsby-config` を修正

```
  plugins: [{
      resolve: `gatsby-plugin-manifest`,
      options: {
        icon: 'src/contents/images/favicon.png',
      }
    },
```

最初 `favicon.ico` として追加したが、[.ico は sharp がサポートしていない](https://community.netlify.com/t/error-input-file-contains-unsupported-image-format-gatsby/10891/3) という書き込みがあり、.png に変更してみたが、エラーは解消されなかった。

ちなみに、ローカル (OSX Catalina) では `yarn build` できました。

**Comment by kaizumaki** [comment]
私の手元ローカル（OSX BigSur）でyarn buildしたらコケますね。Actionsと同じ以下のエラーが出てます。
` Error: Input file contains unsupported image format`

favicon.pngが壊れている可能性があります。試しにgatsby-config.jsの `favicon.png` を同じフォルダにある `github.png` に書き換えたらbuildが通りました。
