### ISSUE TITLE
OGP画像をつけたい

### ISSUE THREAD

**Issue by halsk** [codeforjapan/bad-opendata-temple#127]
シェアしたときに画像が出ないので

**Comment by forestgtree** [comment]
用意してみました🙏 どうでしょうか？
![BOD供養寺_OGP](https://user-images.githubusercontent.com/55567929/102709334-0005e200-42ed-11eb-84a6-0be32a494e7f.png)

**Figma素材**
https://www.figma.com/file/AV1Sd5lGPVAVdrswmi2O9l/BOD%E4%BE%9B%E9%A4%8A%E5%AF%BA?node-id=683%3A37179

**Comment by halsk** [comment]
ありがとうございます！とても素敵です。どなたか実装いただけると嬉しいなぁー
