### ISSUE TITLE
再び供養寺崩壊

### ISSUE THREAD

**Issue by otkzh** [codeforjapan/bad-opendata-temple#181]
トップページにアクセスすると寺が潰れている
macOS Big Sur v11.1 / Chromeバージョン: 87.0.4280.88

<img width="1226" alt="スクリーンショット 2021-01-03 12 15 12" src="https://user-images.githubusercontent.com/6561100/103470993-87f3ed80-4dbd-11eb-95c3-6e27be67bda9.png">
<img width="1226" alt="スクリーンショット 2021-01-03 12 15 48" src="https://user-images.githubusercontent.com/6561100/103470994-8c200b00-4dbd-11eb-8129-38ce972384e3.png">

**Comment by otkzh** [comment]
ローカルでは穏やかな供養寺が
<img width="1190" alt="スクリーンショット 2021-01-03 12 49 59" src="https://user-images.githubusercontent.com/6561100/103471320-41ed5880-4dc2-11eb-9c29-b206dfb3c0bf.png">

**Comment by otkzh** [comment]
momentのdayOfYearは1始まりとのことなので、
https://momentjs.com/docs/#/get-set/day-of-year/

isSanganichiは1/3からはfalseになりますね
```javascript
const isSanganichi = currentTime.isBetween(
  moment().startOf('year').dayOfYear(0),
  moment().startOf('year').dayOfYear(3),
);
```

**Comment by halsk** [comment]
一旦 `dayOfYear(4)` にして直しました。
そもそもこのメソッドが false だったとしても崩壊しないようにしたいところ

**Comment by yokinist** [comment]
> そもそもこのメソッドが false だったとしても崩壊しないようにしたいところ

間違いないですね・・・今も再び起きてしまっているので確認します！
