### ISSUE TITLE
Helmet のタイトル、メタデータなどを正しいものにする

### ISSUE THREAD

**Issue by osoken** [codeforjapan/bad-opendata-temple#20]
@ocean3fish こちら、サイトのメタデータの title, description, keywords の文言お願いします！

**Comment by ocean3fish** [comment]
- title
BADオープンデータ供養寺

- description
「BADオープンデータ供養寺」は世の中に災厄をもたらすBADなデータが二度とこの世を彷徨わないように「供養（データクレンジング）」するために建立されました。

- keywords
オープンデータ, データ活用, データクレンジング, データエンジニアリング, データマネジメント, シビックテック, Code for Japan

@osoken こちらでいかがでしょうかー

**Comment by osoken** [comment]
了解です！やってみますー
