### ISSUE TITLE
寄進者（コントリビューター）の名前を玉垣？石柱？っぽく並べる

### ISSUE THREAD

**Issue by ocean3fish** [codeforjapan/bad-opendata-temple#28]
- フッターに表示するのが良いか
- GitHubアカウント名かな

※イメージ
![tamagaki](https://user-images.githubusercontent.com/4206675/97772294-25962b00-1b89-11eb-9f94-beb8c1816471.jpg)
![tamagaki_2](https://user-images.githubusercontent.com/4206675/97772293-2333d100-1b89-11eb-99af-5e7d1930702f.jpg)

**Comment by osoken** [comment]
`packages.json` の `contributors` 属性を読んで、並べるようにしたい

**Comment by kaizumaki** [comment]
デザインはこんな感じ。

![スクリーンショット 2020-11-07 14 02 42](https://user-images.githubusercontent.com/14883063/98432481-0572e880-2102-11eb-805f-c61d4e47dc45.png)
[Figma](https://www.figma.com/file/AV1Sd5lGPVAVdrswmi2O9l/BOD%E4%BE%9B%E9%A4%8A%E5%AF%BA?node-id=65%3A0)

**Comment by osoken** [comment]
packages.json の contributors 属性を読み込む調査から
