### ISSUE TITLE
住職をアニメーションさせる

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/bad-opendata-temple#3]
- 住職が端から出てきて横切っていくみたいな
- gifアニメ？
- 何かいい方法があればアイディア募集

**Comment by AkitoshiTei** [comment]
マウスオーバーさせるとアニメーションや何かセリフが書かれた吹き出しが現れるのは？

**Comment by kaizumaki** [comment]
とりあえず、#98 で顔のアニメーションを実現しました。
