### ISSUE TITLE
お経を流す

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/bad-opendata-temple#33]
音声ファイルを流す仕組みを実装したいです。
[Webamp](https://github.com/captbaritone/webamp)がよさそうですが、他に方法があればぜひ。

**Comment by kaizumaki** [comment]
対応します。Webampで試します。

**Comment by kaizumaki** [comment]
Webamp、cssがなんとも制御できず...辛かったのであきらめます...
悔しいですが、モダンな見た目の[React H5 Audio Player](https://github.com/lhz516/react-h5-audio-player) にしました。無念。
アイコンくらいなら変更できるみたいです。
https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts--custom-icons

**Comment by MaySoMusician** [comment]
Webamp もしかしたらWinampのスキンファイルを導入する形式かも？
[ここのサイト](https://www.ne.jp/asahi/ma-kun/ore/skinm.html)に「WinampSKIN作成TIPS（zipファイル）」なるものが...
余談ですがこのサイトも結構懐かしい感じ（最終更新2003年）

**Comment by kaizumaki** [comment]
@MaySoMusician なるほどですね。positionのcssを変えるだけでよかったんですけどねー...
余力があればSKINも試したいところです。

**Comment by AkitoshiTei** [comment]
昔のサイトみたいにMIDIで・・・
音が流れるのをなかなか止められない様にとかw
