### ISSUE TITLE
カーソルをローソクにする

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/bad-opendata-temple#4]
参考：[cursor プロパティでの URL 値の使用](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Basic_User_Interface/Using_URL_values_for_the_cursor_property)

**Comment by nichesuch** [comment]
こういうやつですね
https://gifmagazine.net/post_images/3432154
※ライセンス不明

**Comment by nichesuch** [comment]
これやってます！

**Comment by kaizumaki** [comment]
#58 のマージによりクローズします。
