### ISSUE TITLE
文字を流れるようにする（MARQUEE）

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/bad-opendata-temple#6]
- 昔懐かしのアレです
- reactのコンポーネントで実装したい

**Comment by Kanahiro** [comment]
古き良き<MARQUEE>タグはHTML5では廃止されたので別の手法を検討

- CSSからのアプローチ
https://qiita.com/nissuk/items/7d5545a9f6177ff965dc
CSS内で@keyframesを定義する必要があるよう、だがReactでCSSファイルをimportするなら型定義が必要のよう

- 既存モジュール
https://github.com/jasonslyvia/react-marquee
https://github.com/cdtinney/react-double-marquee
有望そうなのが上記2つ、型定義はないのでanyで入れてみたがimportするだけでは動作せず

**Comment by kaizumaki** [comment]
@Kanahiro 調査ありがとうございます！私のほうでチャレンジしてみますね。
