### ISSUE TITLE
紅白餅のGIF作成

### ISSUE THREAD

**Issue by Yfuruchin** [codeforjapan/bad-opendata-temple#89]
オープンデータコミュニティにおけるミーム（）の一つである「餅」と建立をセレブレーションする意味を米て紅白餅のGIFをつくる。仕様は以下のとおり

- GIF形式
- 紅白（桃白）
- 可能ならアニメーション
- 祝の字が入っている

**Comment by Yfuruchin** [comment]
- サイズは32x32を目指す

**Comment by Yfuruchin** [comment]
- 寿も入っているとなおよい

**Comment by Yfuruchin** [comment]
Pushしてみた

https://github.com/codeforjapan/bad-opendata-temple/pull/91

![mochi_red_kotobukii](https://user-images.githubusercontent.com/4961152/99043546-bfba9200-25d1-11eb-829f-aa87e2310f98.gif)
![mochi_white_iwai](https://user-images.githubusercontent.com/4961152/99043553-c0ebbf00-25d1-11eb-8c75-9a7f7f3a5eea.gif)

**Comment by kaizumaki** [comment]
いいですね！せっかくなので、出席いただいたみなさんが持ち帰り（ダウンロード）できるようにしたいですね。

**Comment by kaizumaki** [comment]
#91 のマージによりクローズします。合掌 🙏
