### ISSUE TITLE
餅を投げる

### ISSUE THREAD

**Issue by nichesuch** [codeforjapan/bad-opendata-temple#90]
寺をクリックすると上から餅を投げられるようにする。

少し上方向で、横方向はランダムなベクトルを入力すれば、放物線を描いて落ちていく。

餅自体は以下の作成を待つ。
#89 

アナリティクスでイベント収集も出来るか？

**Comment by Yfuruchin** [comment]
![Nov-13-2020 13-17-38](https://user-images.githubusercontent.com/4961152/99028265-aeae5880-25b2-11eb-9998-0912034cc25a.gif)
動きとしてはファミコン版忍者ハットリくんのボーナスステージぐらいの節操のなさがのぞましい（可能なら）

**Comment by halsk** [comment]
#137 にて、餅を投げる機能が実装されました！寺の扉をクリックすると住職が餅をまいてくれます。もう一度クリックすると消えます。
PCのみの機能です。
![d85e5e0ba8fc1674bdd7a68b563f07e7](https://user-images.githubusercontent.com/16509/101986937-6c248c80-3cd4-11eb-92f7-779f069f47d6.gif)

ちなみに、以下のような方法で実現しています。

* 背景と寺を別画像に分離
* React Transition Group で住職を出現させる
* State 管理で餅のインスタンスを生成
* Stylie を使って餅の奇跡の keyframe を作成して反映
* Props を使って、餅の左右の方向を反転

OSX Safari/Chrome のみ確認。

**Comment by Yfuruchin** [comment]
バラマキ具合の節操がなさがすばらしいLGTM!
